# Rainforest build configoration

compiler_version = "1.0.0"

project_root = "test_project"
main_file = "src/org/alex_hashtag/Main.toucan"

# Detailed Metadata
[metadata]
project_name = "Toucan Test Project"
description = "A project to test the compilation of Toucan projects"

# Author Details
[metadata.author]
name = "Alexander"
email = "alex_hashtag@toucan.wiki"
website = "https://toucan.wiki"

# Version Control
[metadata.version_control]
version = "1.0.0"
repository = "https://github.com/Alex-Hashtag/ToucanCompilerJava"

# Build Configuration
[build]
# Optimization Levels: -O0, -O1, -O2, -Os, -Oz, -O3, -O4
optimization = "-O3"

# Output Settings
[build.output]
executable = "build/output/my_project_executable"
logs = "build/logs"
intermediate_files = "build/intermediate"

# Target Platform
[build.target]
os = "linux"
architecture = "x86_64"

# Additional Build Options
[build.options]
debug_symbols = false