name: Java CI with GraalVM and Native Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    # Step 1: Check out the code
    - name: Check out code
      uses: actions/checkout@v4

    # Step 2: Set up GraalVM JDK 21
    - name: Set up GraalVM with JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'graalvm'
        cache: gradle

    # Step 3: Set required environment variables for GraalVM native-image
    - name: Set environment variables for Native Image
      run: |
        echo "JAVA_HOME=${{ steps.setup-java.outputs.java-home }}" >> $GITHUB_ENV
        echo "PATH=${{ steps.setup-java.outputs.java-home }}/bin:$PATH" >> $GITHUB_ENV

    # Step 4: Set up Gradle
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      with:
        gradle-version: '8.3'

    # Step 5: Build the project with Gradle Wrapper
    - name: Build with Gradle Wrapper
      run: ./gradlew build

    # Step 6: Build native image using GraalVM Native Image
    - name: Build Native Image
      run: ./gradlew nativeCompile

    # Step 7: Upload the artifact (optional)
    - name: Upload Native Image
      uses: actions/upload-artifact@v3
      with:
        name: native-image
        path: build/native-image/

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    # Step 1: Check out the code
    - name: Check out code
      uses: actions/checkout@v4

    # Step 2: Set up GraalVM JDK 21
    - name: Set up GraalVM with JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'graalvm'

    # Step 3: Submit dependency graph for Dependabot
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
